#server:
#  port: 8761
#
#eureka:
#  instance:
#    hostname: 127.0.0.1
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#     defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
server:
  port: 8762

eureka:
 instance:
    hostname: discovery2
 client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://discovery1:8761/eureka/
 server:
    waitTimeInMsWhenSyncEmpty: 0
