#server:
#  port: 8000
##配置数据库，使用SpringJPA
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/microservice
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: update  #分为四种。create，create-drop，update，validate
#      #方便调试，展示sql
#    show-sql: true
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://discovery:8761/eureka/
#    instance:
#      preferIpAddress: true
server:
  port: 8001
spring:
  application:
    name: microservice-provider-user    # 项目名称尽量用小写
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                         # 指定数据源
    platform: mysql                        # 指定数据源类型
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: 123456
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery1:8761/eureka/,http://discovery2:8762/eureka/    # 指定注册中心的地址
  instance:
    preferIpAddress: true